# Generated by Django 6.0 on 2026-01-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_c6dd84_idx',
            old_name='orders_orde_status_4b7a9e_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_table_i_37b1ad_idx',
            old_name='orders_orde_table_i_ccc5a3_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_created_0e92de_idx',
            old_name='orders_orde_created_18f5e3_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_status_8bcdc9_idx',
            old_name='orders_orde_status_d2bf2e_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_station_bb4632_idx',
            old_name='orders_orde_station_1f3e8a_idx',
        ),
    ]
